apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon
  labels:
    app: amazon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
      containers:
      - name: amazon
        image: hemanthkumarms/amazon:latest
        ports:
        - containerPort: 3000